import type { Permission, UserRole } from '../types/auth'

export const ALL_PERMISSIONS: Permission[] = [
  'contacts:read', 'contacts:create', 'contacts:update', 'contacts:delete', 'contacts:export',
  'companies:read', 'companies:create', 'companies:update', 'companies:delete',
  'deals:read', 'deals:create', 'deals:update', 'deals:delete', 'deals:move',
  'activities:read', 'activities:create', 'activities:update', 'activities:delete',
  'email:read', 'email:send', 'email:update', 'email:link',
  'reports:read', 'reports:export',
  'templates:read', 'templates:create', 'templates:update', 'templates:delete',
  'products:read', 'products:create', 'products:update', 'products:delete',
  'automations:read', 'automations:create', 'automations:update', 'automations:delete',
  'sequences:read', 'sequences:create', 'sequences:update', 'sequences:delete', 'sequences:enroll',
  'custom_fields:read', 'custom_fields:update',
  'ai:use',
  'settings:read', 'settings:update',
  'users:read', 'users:create', 'users:update', 'users:delete', 'users:manage_roles', 'users:invite',
  'audit:read',
  'goals:read', 'goals:create', 'goals:update', 'goals:delete',
  'import:csv', 'import:json',
]

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  admin: [
    'contacts:read', 'contacts:create', 'contacts:update', 'contacts:delete', 'contacts:export',
    'companies:read', 'companies:create', 'companies:update', 'companies:delete',
    'deals:read', 'deals:create', 'deals:update', 'deals:delete', 'deals:move',
    'activities:read', 'activities:create', 'activities:update', 'activities:delete',
    'email:read', 'email:send', 'email:update', 'email:link',
    'reports:read', 'reports:export',
    'templates:read', 'templates:create', 'templates:update', 'templates:delete',
    'products:read', 'products:create', 'products:update', 'products:delete',
    'automations:read', 'automations:create', 'automations:update', 'automations:delete',
    'sequences:read', 'sequences:create', 'sequences:update', 'sequences:delete', 'sequences:enroll',
    'custom_fields:read', 'custom_fields:update',
    'ai:use',
    'settings:read', 'settings:update',
    'users:read', 'users:create', 'users:update', 'users:delete', 'users:manage_roles', 'users:invite',
    'audit:read',
    'goals:read', 'goals:create', 'goals:update', 'goals:delete',
    'import:csv', 'import:json',
  ],
  manager: [
    'contacts:read', 'contacts:create', 'contacts:update', 'contacts:delete', 'contacts:export',
    'companies:read', 'companies:create', 'companies:update', 'companies:delete',
    'deals:read', 'deals:create', 'deals:update', 'deals:delete', 'deals:move',
    'activities:read', 'activities:create', 'activities:update', 'activities:delete',
    'email:read', 'email:send', 'email:update', 'email:link',
    'reports:read', 'reports:export',
    'templates:read', 'templates:create', 'templates:update', 'templates:delete',
    'products:read', 'products:create', 'products:update',
    'automations:read', 'automations:create', 'automations:update',
    'sequences:read', 'sequences:create', 'sequences:update', 'sequences:enroll',
    'custom_fields:read', 'custom_fields:update',
    'ai:use',
    'settings:read',
    'users:read', 'users:invite',
    'audit:read',
    'goals:read', 'goals:create', 'goals:update', 'goals:delete',
    'import:csv', 'import:json',
  ],
  sales_rep: [
    'contacts:read', 'contacts:create', 'contacts:update',
    'companies:read', 'companies:create', 'companies:update',
    'deals:read', 'deals:create', 'deals:update', 'deals:move',
    'activities:read', 'activities:create', 'activities:update', 'activities:delete',
    'email:read', 'email:send', 'email:update', 'email:link',
    'reports:read',
    'templates:read',
    'products:read',
    'automations:read',
    'sequences:read', 'sequences:enroll',
    'custom_fields:read',
    'ai:use',
    'goals:read',
  ],
  viewer: [
    'contacts:read',
    'companies:read',
    'deals:read',
    'activities:read',
    'email:read',
    'reports:read',
    'templates:read',
    'products:read',
    'automations:read',
    'sequences:read',
    'custom_fields:read',
    'goals:read',
  ],
}
